# Generated by Django 5.0.2 on 2024-10-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIbranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finame', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.CharField(max_length=25)),
                ('applicantname', models.CharField(max_length=100)),
                ('applicant_mobile_number', models.PositiveBigIntegerField(max_length=10)),
                ('finame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pma.fibranch')),
            ],
        ),
    ]
