# Generated by Django 5.0.2 on 2024-10-16 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 22, 21, 9, 967110)),
        ),
        migrations.AddField(
            model_name='cases',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
